//
// Created by emilianotca on 08-Jul-21.
//

#ifndef REALOCACAO_INTERPLANETARIA_TESTCASES_H
#define REALOCACAO_INTERPLANETARIA_TESTCASES_H

void test_Element();

#endif //REALOCACAO_INTERPLANETARIA_TESTCASES_H
